### ISSUE TITLE
Detect profane usernames

### ISSUE THREAD

**Issue by ddugovic** [domino14/liwords#432]
[REDACTED screenshot]

**Comment by jvc56** [comment]
We will deploy moderation tools that will allow us to hide profane usernames and hopefully mitigate this problem. We have decided to make this a low priority for now since any filter we can think of will become a game of Whac-A-Mole for which we will just need to use our moderation tools to solve anyway. If there is an algorithm that can effectively filter profane usernames and sufficiently solves the Scunthorpe problem, we are not aware of it. Any insights about the problem are appreciated.

**Comment by ddugovic** [comment]
Fair point; there are actually multiple phases of a solution:
1. Flag potential ToS violations for manual review (as you are going to do; and yes there is some whack-a-mole)

2. Semi-automation for example https://www.mturk.com/ - comic https://xkcd.com/1897/
![image](https://user-images.githubusercontent.com/1834123/108875715-15380f00-75c3-11eb-95b1-c77030b03292.png)

3. Full automation which is infeasible - comic https://xkcd.com/1319/
![image](https://user-images.githubusercontent.com/1834123/108875668-08b3b680-75c3-11eb-8b4a-f1335af701b1.png)
